const $=s=>document.querySelector(s);let state={user:JSON.parse(localStorage.user||'null'),tab:'home',shops:[],products:[],cart:[],orders:[],summary:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function api(url,opt={}){let r=await fetch(url,{headers:{'Content-Type':'application/json'},...opt});let x=await r.json();if(!r.ok)throw Error(x.error||'Request failed');return x}
function toast(m){let t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
async function login(){let role=$('#role').value,phone=$('#phone').value,pin=$('#pin').value;try{let x=await api('/api/login',{method:'POST',body:JSON.stringify({role,phone,pin})});state.user=x.user;localStorage.user=JSON.stringify(x.user);render()}catch(e){toast(e.message)}}
function loginView(){return `<div class="login"><div class="card"><div class="logo">Lateri Home Delivery Partner</div><p class="muted">Customer • Shop • Delivery • Admin</p><div class="stack"><select id="role" class="field"><option value="customer">Customer</option><option value="shop">Shop</option><option value="delivery">Delivery Partner</option><option value="admin">Admin</option></select><input id="phone" class="field" placeholder="Mobile number" value="9999999993"><input id="pin" class="field" placeholder="PIN" type="password" value="3333"><button onclick="login()">Login</button><p class="small muted">Demo access: Customer 9999999993/3333 • Shop 9999999991/1111 • Delivery 9999999992/2222 • Admin 9999999999/1234</p></div></div></div>`}
async function load(){if(!state.user)return;state.shops=(await api('/api/shops')).shops;state.products=(await api('/api/products')).products;if(state.user.role==='admin')state.summary=await api('/api/admin/summary');state.orders=(await api('/api/orders?role='+state.user.role+'&userId='+state.user.id+'&shopId='+(state.user.shopId||''))).orders}
function customer(){let shops=state.shops.map(s=>`<div class="card"><div class="row"><div><h3>${esc(s.name)}</h3><div class="muted">${esc(s.category)} • ${esc(s.eta)}</div></div><button onclick="shop('${s.id}')">View</button></div></div>`).join('');let cartTotal=state.cart.reduce((a,x)=>a+x.price*x.qty,0);return `<div class="hero"><h1>Lateri Home Delivery Partner</h1><p>📍 ${esc(state.user.address||'Lateri, Madhya Pradesh')}</p><button onclick="checkout()">🛒 Cart (${state.cart.reduce((a,x)=>a+x.qty,0)}) ₹${cartTotal}</button></div><h2>Nearby Shops</h2>${shops}<h2>My Orders</h2>${ordersHtml()}`}
function shop(sid){let s=state.shops.find(x=>x.id===sid),ps=state.products.filter(x=>x.shopId===sid);$('#app').innerHTML=`<div class="app"><div class="top"><button onclick="render()">← Back</button><div class="brand">${esc(s.name)}</div></div><div class="grid">${ps.map(p=>`<div class="card"><h3>${esc(p.name)}</h3><div class="muted">${p.stock} ${esc(p.unit)} available</div><p class="price">₹${p.price}</p><button ${p.stock<1?'disabled':''} onclick='add(${JSON.stringify(p)})'>Add</button></div>`).join('')}</div><div id="toast" class="toast"></div></div>`}
function add(p){let x=state.cart.find(x=>x.productId===p.id);if(x)x.qty++;else state.cart.push({productId:p.id,name:p.name,price:p.price,qty:1});toast('Cart updated')}
async function checkout(){if(!state.cart.length)return toast('Cart empty');let sid=state.products.find(p=>p.id===state.cart[0].productId).shopId;let ok=confirm('COD order place karein? Total ₹'+state.cart.reduce((a,x)=>a+x.price*x.qty,0));if(!ok)return;try{await api('/api/orders',{method:'POST',body:JSON.stringify({customerId:state.user.id,customerName:state.user.name,phone:state.user.phone,address:state.user.address,shopId:sid,items:state.cart,payment:'COD'})});state.cart=[];await load();toast('Order placed');render()}catch(e){toast(e.message)}}
function ordersHtml(){return state.orders.length?state.orders.map(o=>`<div class="card"><div class="row"><b>${esc(o.id)}</b><span class="pill status">${esc(o.status)}</span></div><p>${esc(o.shopName)} • ₹${o.total}</p><div class="small muted">${new Date(o.createdAt).toLocaleString()}</div></div>`).join(''):'<p class="muted">No orders yet.</p>'}
async function updateOrder(id,status,deliveryId){try{await api('/api/orders/'+id,{method:'PATCH',body:JSON.stringify({status,deliveryId})});await load();render();toast('Order updated')}catch(e){toast(e.message)}}
function shopDash(){let ps=state.products.filter(p=>p.shopId===state.user.shopId);return `<div class="hero"><h1>Shop Panel</h1><p>${esc(state.user.name)}</p></div><h2>New / Active Orders</h2>${state.orders.map(o=>`<div class="card"><div class="row"><b>${esc(o.id)}</b><span class="pill">${esc(o.status)}</span></div><p>${o.items.map(i=>esc(i.name)+' × '+i.qty).join(', ')}</p><p>₹${o.total} • ${esc(o.address)}</p><div class="tabs">${['confirmed','packed','ready_for_delivery'].map(st=>`<button onclick="updateOrder('${o.id}','${st}')">${st}</button>`).join('')}</div></div>`).join('')||'<p class="muted">No orders.</p>'}<h2>Products</h2><div class="card"><div class="stack"><input id="pn" class="field" placeholder="Product name"><input id="pp" class="field" placeholder="Price" type="number"><input id="ps" class="field" placeholder="Stock" type="number"><button onclick="addProduct()">Add Product</button></div></div>${ps.map(p=>`<div class="card"><div class="row"><b>${esc(p.name)}</b><span>₹${p.price}</span></div><div class="muted">Stock: ${p.stock}</div></div>`).join('')}`}
async function addProduct(){try{await api('/api/shop/products',{method:'POST',body:JSON.stringify({shopId:state.user.shopId,name:$('#pn').value,price:$('#pp').value,stock:$('#ps').value})});await load();render();toast('Product added')}catch(e){toast(e.message)}}
function deliveryDash(){return `<div class="hero"><h1>Delivery Partner</h1><p>Ready for delivery orders</p></div>${state.orders.map(o=>`<div class="card"><div class="row"><b>${esc(o.id)}</b><span class="pill">${esc(o.status)}</span></div><p>🏪 ${esc(o.shopName)}</p><p>📍 ${esc(o.address)}</p><p>💰 ₹${o.total} • ${esc(o.payment)}</p><div class="tabs">${!o.deliveryId?`<button class="ok" onclick="updateOrder('${o.id}','out_for_delivery','${state.user.id}')">Accept & Start</button>`:''}<button class="ok" onclick="updateOrder('${o.id}','delivered','${state.user.id}')">Delivered</button></div></div>`).join('')||'<p class="muted">No delivery orders yet.</p>'}`}
function adminDash(){let s=state.summary||{};return `<div class="hero"><h1>Admin Panel</h1><p>Lateri Home Delivery Partner</p></div><div class="grid"><div class="card"><h2>${s.shops||0}</h2><div>Shops</div></div><div class="card"><h2>${s.products||0}</h2><div>Products</div></div><div class="card"><h2>${s.orders||0}</h2><div>Orders</div></div><div class="card"><h2>₹${s.revenue||0}</h2><div>Revenue</div></div></div><h2>Orders</h2>${state.orders.map(o=>`<div class="card"><div class="row"><b>${esc(o.id)}</b><span class="pill">${esc(o.status)}</span></div><p>${esc(o.shopName)} • ₹${o.total}</p><p>${esc(o.address)}</p></div>`).join('')||'<p class="muted">No orders.</p>'}`}
function render(){if(!state.user){$('#app').innerHTML=loginView();return}load().then(()=>{let body=state.user.role==='customer'?customer():state.user.role==='shop'?shopDash():state.user.role==='delivery'?deliveryDash():adminDash();$('#app').innerHTML=`<div class="app"><div class="top"><div class="brand">Lateri Home Delivery Partner</div><button onclick="logout()">Logout</button></div>${body}<div id="toast" class="toast"></div></div>`}).catch(e=>{$('#app').innerHTML='<div class="app"><div class="card">Error: '+esc(e.message)+'</div></div>'})}
function logout(){localStorage.removeItem('user');state.user=null;render()}
render();
